/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/scene.gltf
Author: defiat11 (https://sketchfab.com/defiat11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anime-table-5d070b32283d47fb897149a7c38bd2a4
Title: Anime Table
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Desktop = (props) => {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI, 0.026, -Math.PI]}>
          <mesh geometry={nodes['Cube_(2)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['Cube_(2)_Color6_0'].geometry} material={materials.Color6} />
        </group>
        <group position={[-55.784, 144.38, -37.7]}>
          <group position={[-2.166, 13.557, 9.05]} rotation={[0, -0.532, 0]}>
            <group position={[0, 32.962, 39.55]} rotation={[0, 1.178, 0]}>
              <group position={[0.06, 8.75, 0.65]} rotation={[-0.201, 0, 0]}>
                <group position={[-0.06, 0.42, 43.6]} rotation={[0.209, 0, 0]}>
                  <group position={[-0.05, -1.845, 7.392]} rotation={[0, 1.056, 0]}>
                    <group position={[0, 0.144, 3.237]}>
                      <group position={[0, 0, 4.11]}>
                        <group position={[0.091, -0.783, 2.356]} rotation={[0, -Math.PI / 2, 0]} scale={1.065}>
                          <mesh geometry={nodes['MOP_Build_(21)_M_tablet_0'].geometry} material={materials.M_tablet} />
                          <mesh geometry={nodes.Cube_M_tablet_0.geometry} material={materials.M_tablet} position={[-5.32, -2.136, -20.9]} />
                          <mesh geometry={nodes['Cube_(10)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-5.32, -4.236, -20.9]} />
                          <mesh geometry={nodes['Cube_(11)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-5.32, -6.236, -20.9]} />
                        </group>
                        <mesh geometry={nodes['MOP_Build_(17)_M_tablet_0'].geometry} material={materials.M_tablet} />
                      </group>
                      <mesh geometry={nodes.Mesh_M_tablet_0.geometry} material={materials.M_tablet} />
                    </group>
                    <mesh geometry={nodes['Mesh_(8)_M_tablet_0'].geometry} material={materials.M_tablet} />
                    <mesh geometry={nodes.Cylinder_M_tablet_0.geometry} material={materials.M_tablet} position={[0.05, 1.845, -7.392]} />
                  </group>
                  <mesh geometry={nodes['Cube_(6)_M_tablet_0'].geometry} material={materials.M_tablet} />
                </group>
                <mesh geometry={nodes['MOP_Build_(16)_M_tablet_0'].geometry} material={materials.M_tablet} />
                <mesh geometry={nodes['Cylinder_(12)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.89, -113.865, 13.618]} scale={[1, 0.57, 0.57]} />
                <mesh geometry={nodes['MOP_Build_(18)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.89, -199.65, -49.25]} />
              </group>
              <group position={[-0.05, 4.46, 6.886]} rotation={[2.906, 0, 0]}>
                <group position={[0, 0.04, -18.914]} rotation={[Math.PI, 0, 0]}>
                  <mesh geometry={nodes['Cylinder_(11)_M_tablet_0'].geometry} material={materials.M_tablet} />
                  <mesh geometry={nodes['Mesh_(6)_M_tablet_0'].geometry} material={materials.M_tablet} position={[0, 0.04, 8.672]} />
                </group>
                <mesh geometry={nodes['Mesh_(7)_M_tablet_0'].geometry} material={materials.M_tablet} />
                <mesh geometry={nodes['Cylinder_(9)_M_tablet_0'].geometry} material={materials.M_tablet} position={[58, 139.32, -0.536]} rotation={[-Math.PI, 0, 0]} scale={[1, 0.695, 0.695]} />
              </group>
              <mesh geometry={nodes['MOP_Build_(15)_M_tablet_0'].geometry} material={materials.M_tablet} />
              <mesh geometry={nodes['Cylinder_(13)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.95, -191.75, -51.95]} />
              <mesh geometry={nodes['Cylinder_(10)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.95, -134.86, -29.678]} scale={[1, 0.695, 0.695]} />
            </group>
            <mesh geometry={nodes['MOP_Build_(14)_M_tablet_0'].geometry} material={materials.M_tablet} />
            <mesh geometry={nodes['MOP_Build_(19)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.95, -157.938, -9.05]} />
          </group>
          <group position={[-2.166, 13.557, -19.15]} rotation={[-Math.PI, -0.595, -Math.PI]}>
            <group position={[0, 32.962, 39.55]} rotation={[-Math.PI, -0.845, Math.PI]}>
              <group position={[0.06, 8.75, 0.65]} rotation={[0.375, 0, 0]}>
                <group position={[-0.06, 0.42, 43.6]} rotation={[-0.305, 0, 0]}>
                  <group position={[-0.05, -1.845, 7.392]} rotation={[0, -0.323, 0]}>
                    <group position={[0, 0.144, 3.237]} rotation={[-0.428, 0, 0]}>
                      <group position={[0, 0, 4.11]}>
                        <group position={[-0.219, -0.783, 2.272]} rotation={[0, -1.562, 0]} scale={1.065}>
                          <mesh geometry={nodes['MOP_Build_(22)_M_tablet_0'].geometry} material={materials.M_tablet} />
                          <mesh geometry={nodes['Cube_(3)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-5.32, -2.136, -20.9]} />
                          <mesh geometry={nodes['Cube_(13)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-5.32, -4.236, -20.9]} />
                          <mesh geometry={nodes['Cube_(12)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-5.32, -6.236, -20.9]} />
                        </group>
                        <mesh geometry={nodes['MOP_Build_(9)_M_tablet_0'].geometry} material={materials.M_tablet} />
                      </group>
                      <mesh geometry={nodes['Mesh_(5)_M_tablet_0'].geometry} material={materials.M_tablet} />
                    </group>
                    <mesh geometry={nodes['Mesh_(3)_M_tablet_0'].geometry} material={materials.M_tablet} />
                    <mesh geometry={nodes['Cylinder_(6)_M_tablet_0'].geometry} material={materials.M_tablet} position={[0.05, 1.845, -7.392]} />
                  </group>
                  <mesh geometry={nodes['Cube_(5)_M_tablet_0'].geometry} material={materials.M_tablet} />
                </group>
                <mesh geometry={nodes['MOP_Build_(7)_M_tablet_0'].geometry} material={materials.M_tablet} />
                <mesh geometry={nodes['Cylinder_(5)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.89, -113.865, 13.618]} scale={[1, 0.57, 0.57]} />
                <mesh geometry={nodes['MOP_Build_(11)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.89, -199.65, -49.25]} />
              </group>
              <group position={[-0.05, 4.46, 6.886]} rotation={[-2.697, 0, 0]}>
                <group position={[0, 0.04, -18.914]} rotation={[-Math.PI, 0, 0]}>
                  <mesh geometry={nodes['Cylinder_(15)_M_tablet_0'].geometry} material={materials.M_tablet} />
                  <mesh geometry={nodes['Mesh_(2)_M_tablet_0'].geometry} material={materials.M_tablet} position={[0, 0.04, 8.672]} />
                </group>
                <mesh geometry={nodes['Mesh_(4)_M_tablet_0'].geometry} material={materials.M_tablet} />
                <mesh geometry={nodes['Cylinder_(14)_M_tablet_0'].geometry} material={materials.M_tablet} position={[58, 139.32, -0.536]} rotation={[-Math.PI, 0, 0]} scale={[1, 0.695, 0.695]} />
              </group>
              <mesh geometry={nodes['MOP_Build_(6)_M_tablet_0'].geometry} material={materials.M_tablet} />
              <mesh geometry={nodes['Cylinder_(8)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.95, -191.75, -51.95]} />
              <mesh geometry={nodes['Cylinder_(3)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.95, -134.86, -29.678]} scale={[1, 0.695, 0.695]} />
            </group>
            <mesh geometry={nodes['MOP_Build_(5)_M_tablet_0'].geometry} material={materials.M_tablet} />
            <mesh geometry={nodes['MOP_Build_(13)_M_tablet_0'].geometry} material={materials.M_tablet} position={[57.95, -157.938, -9.05]} />
          </group>
          <mesh geometry={nodes['MOP_Build_(2)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['MOP_Build_(3)_M_tablet_0'].geometry} material={materials.M_tablet} position={[55.784, -144.38, -10.3]} />
          <mesh geometry={nodes.MOP_Build_M_tablet_0.geometry} material={materials.M_tablet} position={[55.784, -144.38, 0]} />
          <mesh geometry={nodes['Cylinder_(4)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-9.761, -9.985, -18.492]} />
          <mesh geometry={nodes['Cylinder_(7)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-9.761, -10.025, 8.748]} />
        </group>
        <group position={[-4.5, 144.3, 127.4]} rotation={[0, 0.14, 0]} scale={[1, 0.943, 1]}>
          <mesh geometry={nodes['MOP_Build_(24)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['Cube_(7)_M_tablet_0'].geometry} material={materials.M_tablet} position={[4.5, -152.974, -127.4]} scale={[1, 1.06, 1]} />
          <mesh geometry={nodes['Mesh_(33)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['MOP_Build_(25)_(2)_M_tablet_0'].geometry} material={materials.M_tablet} position={[4.5, -155.624, -127.4]} scale={[1, 1.06, 1]} />
        </group>
        <group position={[0, 0, 10.7]}>
          <mesh geometry={nodes['Mesh_(11)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['Mesh_(11)_Keyboard-Metal-01_0'].geometry} material={materials['Keyboard-Metal-01']} />
          <mesh geometry={nodes['Mesh_(11)_Keyboard-Plastic-04_0'].geometry} material={materials['Keyboard-Plastic-04']} />
        </group>
        <group position={[-38.18, 146.493, -52.261]}>
          <mesh geometry={nodes['Mesh_(12)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['Mesh_(12)_Keyboard-Metal-01_0'].geometry} material={materials['Keyboard-Metal-01']} />
          <mesh geometry={nodes['Mesh_(12)_Keyboard-Plastic-04_0'].geometry} material={materials['Keyboard-Plastic-04']} />
        </group>
        <group position={[-51.8, 144.262, 73.4]}>
          <mesh geometry={nodes['MOP_Build_(31)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['Mesh_(34)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['MOP_Build_(34)_M_tablet_0'].geometry} material={materials.M_tablet} position={[0.109, 8.137, -19.114]} scale={[1.065, 1.215, 1.065]} />
          <mesh geometry={nodes['MOP_Build_(35)_M_tablet_0'].geometry} material={materials.M_tablet} position={[0.109, 7.037, -8.654]} scale={[1.065, 1.215, 1.065]} />
          <mesh geometry={nodes['MOP_Build_(36)_M_tablet_0'].geometry} material={materials.M_tablet} position={[0.109, 7.537, 2.196]} scale={[1.065, 1.215, 1.065]} />
          <mesh geometry={nodes['MOP_Build_(37)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-0.091, 7.537, 12.866]} scale={[1.065, 1.215, 1.065]} />
          <mesh geometry={nodes['Cube_(41)_M_tablet_0'].geometry} material={materials.M_tablet} position={[51.8, -144.262, -73.4]} />
        </group>
        <group position={[-53.84, 145.181, 12.79]} scale={[0.248, 0.353, 0.061]}>
          <mesh geometry={nodes['Cube_(26)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['Mesh_(29)_M_tablet_0'].geometry} material={materials.M_tablet} position={[0, 28.159, 0]} scale={[4.033, 2.83, 16.309]} />
        </group>
        <group position={[-4.5, 144.3, 127.4]} rotation={[0, 0.14, 0]} scale={[1, 0.943, 1]}>
          <mesh geometry={nodes['MOP_Build_(38)_M_tablet_0'].geometry} material={materials.M_tablet} />
          <mesh geometry={nodes['Cube_(44)_M_tablet_0'].geometry} material={materials.M_tablet} position={[4.5, -152.974, -127.4]} scale={[1, 1.06, 1]} />
          <mesh geometry={nodes['Mesh_(37)_M_tablet_0'].geometry} material={materials.M_tablet} />
        </group>
        <mesh geometry={nodes['Mesh_(10)_M_tablet_0'].geometry} material={materials.M_tablet} />
        <mesh geometry={nodes['Cube_(8)_M_tablet_0'].geometry} material={materials.M_tablet} position={[15.8, 144.579, -77.4]} rotation={[0, 0.215, 0]} scale={0.58} />
        <mesh geometry={nodes['Cube_(14)_M_tablet_0'].geometry} material={materials.M_tablet} position={[22.8, 144.6, -30]} rotation={[0, -0.07, 0]} scale={[1.48, 1, 1.935]} />
        <mesh geometry={nodes['MOP_Build_(29)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-27.6, 144.638, 48.55]} rotation={[3.127, -0.348, 3.141]} />
        <mesh geometry={nodes['Cylinder_(18)_M_transp_0'].geometry} material={materials.M_transp} position={[13.1, 246.65, 114.2]} />
        <mesh geometry={nodes['Cube_(19)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-17.4, 144.842, 83.9]} rotation={[0, 0.559, 0]} scale={1.15} />
        <mesh geometry={nodes['Cube_(23)_M_transp_0'].geometry} material={materials.M_transp} position={[-19.05, 144.215, -43.95]} rotation={[0, -0.297, 0]} scale={[0.151, 0.099, 0.151]} />
        <mesh geometry={nodes['Mesh_(28)_M_tablet_0'].geometry} material={materials.M_tablet} position={[12.32, 249.153, 114.78]} rotation={[0.166, 0, 0.209]} />
        <mesh geometry={nodes['MOP_Build_(32)_M_tablet_0'].geometry} material={materials.M_tablet} />
        <mesh geometry={nodes['Cube_(33)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-59.117, 126.81, -3.917]} rotation={[0, -0.436, 0]} scale={[0.144, 0.143, 0.144]} />
        <mesh geometry={nodes['Cylinder_(17)_M_tablet_0'].geometry} material={materials.M_tablet} position={[38.8, 144.225, 85.4]} rotation={[0, 0.148, 0]} scale={0.205} />
        <mesh geometry={nodes['Cube_(42)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-28.718, 190.241, 63.59]} rotation={[-1.596, -0.133, -1.425]} scale={[1.105, 1, 1.105]} />
        <mesh geometry={nodes['Cube_(43)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-30.024, 186.927, 55.753]} rotation={[-1.514, -0.088, -1.422]} scale={[1.105, 1, 1.105]} />
        <mesh geometry={nodes['Cube_(45)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-33.888, 189.751, 30.344]} rotation={[-1.524, -0.019, -1.422]} scale={[1.105, 1, 1.105]} />
        <mesh geometry={nodes['Cylinder_(21)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-41.7, 144.225, -141]} rotation={[Math.PI, -1.314, -Math.PI]} scale={0.166} />
        <mesh geometry={nodes['Mesh_(39)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-51.6, 135.962, 39.15]} />
        <mesh geometry={nodes['Mesh_(41)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-49.7, 144.996, 32.45]} scale={[0.968, 0.988, 0.51]} />
        <mesh geometry={nodes['Mesh_(43)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-49.065, 145.296, 18.65]} rotation={[0.192, 0, 0]} scale={[0.605, 0.735, 0.66]} />
        <mesh geometry={nodes['Mesh_(42)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-52.765, 145.276, 23.45]} rotation={[0.166, 0, 0]} scale={[0.766, 0.87, 0.87]} />
        <mesh geometry={nodes['Mesh_(30)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-53.1, 145.396, 27.85]} rotation={[0.061, 0, -0.035]} scale={[0.968, 0.988, 0.51]} />
        <mesh geometry={nodes['Mesh_(31)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-54.165, 145.296, 14.7]} rotation={[0.209, 0, 0]} scale={[0.605, 0.735, 0.614]} />
        <mesh geometry={nodes['Cube_(15)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-88.5, 112.5, 0]} />
        <mesh geometry={nodes['Cube_(21)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-88.5, 112.5, 95.2]} rotation={[-Math.PI / 6, 0, 0]} />
        <mesh geometry={nodes['Cylinder_(20)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-37.694, 165.936, 34.96]} rotation={[-0.052, 0, 0]} />
        <mesh geometry={nodes['Mesh_(38)_M_tablet_0'].geometry} material={materials.M_tablet} />
        <mesh geometry={nodes['Cylinder_(23)_M_tablet_0'].geometry} material={materials.M_tablet} position={[14.2, 144.225, 89]} rotation={[0, -0.492, 0]} scale={0.257} />
        <mesh geometry={nodes['Mesh_(45)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-13.2, 144.4, -89.4]} />
        <mesh geometry={nodes['MOP_Build_(40)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-29.4, 144.33, 28]} rotation={[0, -0.157, 0]} scale={0.47} />
        <mesh geometry={nodes['MOP_Build_(41)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-25.25, 144.73, 25.45]} rotation={[0, 0.401, -0.052]} scale={0.47} />
        <mesh geometry={nodes['MOP_Build_(42)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-25.25, 144.73, 32.35]} rotation={[0, -0.253, -0.052]} scale={0.47} />
        <mesh geometry={nodes['Cube_(28)_M_tablet_0'].geometry} material={materials.M_tablet} position={[26.2, 217.578, 100.357]} rotation={[-1.456, 0.077, 0.149]} scale={[1.105, 1, 1.105]} />
        <mesh geometry={nodes['Cube_(31)_M_tablet_0'].geometry} material={materials.M_tablet} position={[3.076, 174.349, -122.727]} rotation={[0.019, -0.462, 0.383]} scale={[0.3, 0.288, 0.227]} />
        <mesh geometry={nodes['Cube_(27)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-31.5, 144.967, 13]} rotation={[-Math.PI, -0.467, -Math.PI]} scale={0.95} />
        <mesh geometry={nodes['Cube_(29)_M_tablet_0'].geometry} material={materials.M_tablet} position={[41.392, 172.8, 133.987]} rotation={[0, -1.441, 0]} scale={1.088} />
        <mesh geometry={nodes['Mesh_(32)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-57.013, 160.285, -7.569]} rotation={[-3.029, 0.158, 2.502]} scale={0.73} />
        <mesh geometry={nodes['Mesh_(40)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-37.183, 165.96, 34.93]} rotation={[-2.199, 0.66, 2.939]} scale={0.357} />
        <mesh geometry={nodes['Cube_(30)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-48.9, 145.747, 3.92]} rotation={[0, -0.563, 0]} scale={0.95} />
        <mesh geometry={nodes['Cube_(32)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-23.45, 150.467, -41.5]} rotation={[0, -1.13, 0]} scale={0.95} />
        <mesh geometry={nodes.Cube_160_M_tablet_0.geometry} material={materials.M_tablet} position={[-39.4, 144.094, -128.9]} rotation={[-Math.PI, 1.449, -Math.PI]} scale={0.54} />
        <mesh geometry={nodes['Cube_160_(2)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-31.75, 144.094, -129.55]} rotation={[-Math.PI, 0.332, -Math.PI]} scale={0.54} />
        <mesh geometry={nodes['Cube_160_(3)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-40.8, 144.174, -121.6]} rotation={[0, 1.124, 0]} scale={0.54} />
        <mesh geometry={nodes['Cylinder_(2)_M_tablet_0'].geometry} material={materials.M_tablet} position={[-54, 144.225, -124.4]} rotation={[Math.PI, -1.314, -Math.PI]} scale={0.166} />
        <mesh geometry={nodes['Cube_160_(4)_M_tablet_0'].geometry} material={materials.M_tablet} position={[25.4, 144.544, -111.6]} rotation={[-0.212, 1.118, 0.048]} scale={0.54} />
        <mesh geometry={nodes['Mesh_(9)_M_tablet_0'].geometry} material={materials.M_tablet} />
      </group>
    </group>
  )
}

export default Desktop;

useGLTF.preload('/scene.gltf')
